### ISSUE TITLE
unable to pull from docker

### ISSUE THREAD

**Issue by royharoush** [nccgroup/autopwn#11]
hi, 
unable to pull autopwn from docker.

root@kaliiso:/tmp# docker pull rascal999/autopwn
Using default tag: latest
Pulling repository docker.io/rascal999/autopwn
Error: image rascal999/autopwn:latest not found
root@kaliiso:/tmp#

**Comment by rascal999** [comment]
Hello Roy,

I no longer develop autopwn due to leaving NCC. I now develop a fork called
torc, which you can find at https://github.com/rascal999/torc

Regards,

Aidan M.

**Comment by lllama** [comment]
Hi @royharoush 

We will be moving this to an official NCC Docker repo in the near future. I'll update this issue when we have.

**Comment by royharoush** [comment]
thank you for the update.
