### ISSUE TITLE
autopwn-cli repository doesn't exist?

### ISSUE THREAD

**Issue by 0x646e78** [nccgroup/autopwn#12]
README links to https://github.com/rascal999/autopwn-cli but there is no repository of that name.  Searching github doesn't bring up any hits.  Looks like -gui is the same.

Keen to try out this project, but will await some advice as to where these projects are available from (or possibly they're integrated somehow now?).

**Comment by rascal999** [comment]
I don't support autopwn anymore. I now maintain a project called torc, but neither project has a CLI.
